import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { config as loadDotenv } from 'dotenv';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const repoRoot = resolve(root, '..');

// dotenv does not override existing process.env (Docker ARG/ENV, Vercel win).
if (existsSync('/.dockerenv')) {
  loadDotenv({ path: resolve(root, '.env'), quiet: true });
}
loadDotenv({ path: resolve(repoRoot, '.env.docker'), quiet: true });

const apiBaseUrl = (
  process.env.NG_APP_API_BASE_URL?.trim() ||
  process.env.API_PUBLIC_URL?.trim() ||
  process.env.API_URL?.trim() ||
  'http://localhost:3000'
).replace(/\/+$/, '');

const escape = (value) => value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

const content = `// Auto-generated by scripts/generate-env.mjs (dotenv + process.env) — do not edit.
// Regenerated when you run \`npm start\` or \`npm run build\`.

export const ENV = {
  NG_APP_API_BASE_URL: '${escape(apiBaseUrl)}',
} as const;
`;

const outDir = resolve(root, 'src/app/core/config');
mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, 'env.generated.ts'), content, 'utf8');

console.log('[env] NG_APP_API_BASE_URL:', apiBaseUrl);
