-- Migration: SO Number Redesign
-- Description: Creates the tblso_number_sequences table for tracking monthly SO number sequences
-- Requirements: 3.1, 3.2, 3.3, 3.4

-- =============================================================================
-- Step 1: Create the SO number sequences table
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.tblso_number_sequences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year_month VARCHAR(7) NOT NULL,  -- Format: 'YYYY-MM' (e.g., '2026-06')
  last_sequence INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_so_sequences_year_month UNIQUE (year_month),
  CONSTRAINT chk_sequence_range CHECK (last_sequence >= 0 AND last_sequence <= 99999)
);

CREATE INDEX IF NOT EXISTS idx_so_sequences_year_month ON public.tblso_number_sequences(year_month);

-- =============================================================================
-- Step 2: Migrate so_number from GENERATED ALWAYS AS STORED to regular TEXT
-- Requirements: 2.1, 2.2, 2.3, 2.4, 4.1
-- =============================================================================
-- PostgreSQL does not allow ALTER COLUMN to drop the generation expression directly,
-- so we use a two-step approach: add temporary column, copy data, drop original, rename.

-- 2a. Add a temporary column to hold existing values
ALTER TABLE public.tblsales_order ADD COLUMN so_number_new TEXT;

-- 2b. Copy existing generated values into the new column
UPDATE public.tblsales_order SET so_number_new = so_number;

-- 2c. Drop the generated column
ALTER TABLE public.tblsales_order DROP COLUMN so_number;

-- 2d. Rename the new column to so_number
ALTER TABLE public.tblsales_order RENAME COLUMN so_number_new TO so_number;

-- =============================================================================
-- Step 3: Add constraints on the migrated so_number column
-- =============================================================================

-- NOT NULL constraint ensures all sales orders must have an SO number
ALTER TABLE public.tblsales_order ALTER COLUMN so_number SET NOT NULL;

-- UNIQUE constraint prevents duplicate SO numbers
ALTER TABLE public.tblsales_order ADD CONSTRAINT uq_sales_order_so_number UNIQUE (so_number);

-- =============================================================================
-- Step 4: Seed the sequence table with the current month's order count
-- =============================================================================
-- This ensures the sequence counter starts from the correct value based on
-- how many orders already exist in the current month.

INSERT INTO public.tblso_number_sequences (year_month, last_sequence)
SELECT
  TO_CHAR(NOW(), 'YYYY-MM'),
  COALESCE(COUNT(*), 0)
FROM public.tblsales_order
WHERE created_at >= DATE_TRUNC('month', NOW())
ON CONFLICT (year_month) DO UPDATE SET last_sequence = EXCLUDED.last_sequence;
