-- ============================================================
-- HVAC Inventory & Sales Management System
-- FULL DATABASE SCHEMA
-- ============================================================
-- Purpose: Creates ALL tables, indexes, triggers, functions, and views
--          needed for a fresh database installation.
--
-- Usage:   Run this FIRST on a new Supabase/PostgreSQL database,
--          then run seed_default_data.sql for initial data.
--
-- Generated: 2026-05-05
-- ============================================================

BEGIN;

-- ============================================================
-- SECTION 1: CORE TABLES
-- ============================================================

-- 1.1 Branches
CREATE TABLE IF NOT EXISTS public.tblbranches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "branchName" VARCHAR(255) NULL,
  "branchAddress" TEXT NULL,
  CONSTRAINT tblbranches_id_key UNIQUE (id)
);

-- 1.2 Brands
CREATE TABLE IF NOT EXISTS public.tblbrands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "brandName" VARCHAR NULL,
  prefix VARCHAR NULL,
  type VARCHAR(10) DEFAULT 'ACU' CHECK (type IN ('ACU', 'MAT')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT tblbrands_id_key UNIQUE (id)
);

CREATE INDEX IF NOT EXISTS idx_tblbrands_type ON public.tblbrands(type);

-- 1.3 RBAC Roles
CREATE TABLE IF NOT EXISTS public.tblrbac (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "roleName" VARCHAR(50) UNIQUE,
  "roleMenus" TEXT NULL,
  "rolePermission" TEXT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT tblrbac_id_key UNIQUE (id)
);

-- 1.4 Users
CREATE TABLE IF NOT EXISTS public.tblusers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE,
  password TEXT NULL,
  fullname VARCHAR(100) NULL,
  birthdate DATE NULL,
  address TEXT NULL,
  email VARCHAR(100) NULL,
  contact VARCHAR(50) NULL,
  status SMALLINT NULL,
  is_deleted BOOLEAN NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NULL DEFAULT NOW(),
  created_by BIGINT NULL DEFAULT 1,
  "roleId" BIGINT NULL DEFAULT 1 REFERENCES public.tblrbac(id) ON UPDATE CASCADE ON DELETE SET NULL,
  "branchId" BIGINT NULL REFERENCES public.tblbranches(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT tblusers_id_key UNIQUE (id)
);

-- 1.5 Settings (single-row business config)
CREATE TABLE IF NOT EXISTS public.tblsettings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "businessName" TEXT NULL,
  "businessAddress" TEXT NULL,
  "businessEmail" VARCHAR NULL,
  "businessContact" VARCHAR NULL,
  "businessTIN" VARCHAR NULL,
  "businessOwner" VARCHAR NULL,
  "businessLogo" TEXT NULL,
  "businessLogoLight" TEXT NULL,
  "businessLogoDark" TEXT NULL,
  "drTemplatePdf" TEXT NULL,
  cv_number_prefix TEXT DEFAULT 'CV',
  cv_number_suffix TEXT DEFAULT '',
  gj_number_prefix TEXT DEFAULT 'GJ',
  gj_number_suffix TEXT DEFAULT '',
  website_tab_name TEXT NULL,
  routing_tab_name TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT tblsettings_id_key UNIQUE (id)
);

-- ============================================================
-- SECTION 2: PRODUCTS & INVENTORY
-- ============================================================

-- 2.1 Products
CREATE TABLE IF NOT EXISTS public.tblproducts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "brandId" BIGINT NULL REFERENCES public.tblbrands(id) ON UPDATE CASCADE ON DELETE SET NULL,
  "productName" TEXT NULL,
  "productType" VARCHAR NULL,
  "unitTypes" TEXT NULL,
  unit VARCHAR NULL DEFAULT 'SET',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT NULL,
  updated_at TIMESTAMPTZ NULL,
  updated_by BIGINT NULL,
  deleted_at VARCHAR NULL,
  deleted_by BIGINT NULL,
  CONSTRAINT tblproducts_id_key UNIQUE (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS tblproducts_productname_active_uidx
  ON public.tblproducts ("productName")
  WHERE deleted_at IS NULL;

-- 2.2 Capacity (Product Variants)
CREATE TABLE IF NOT EXISTS public.tblcapacity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "prodId" BIGINT NULL REFERENCES public.tblproducts(id) ON UPDATE CASCADE ON DELETE SET NULL,
  capacity VARCHAR NULL,
  "indoorModel" VARCHAR NULL,
  "outdoorModel" VARCHAR NULL,
  srp DOUBLE PRECISION NULL DEFAULT 0,
  "netPrice" DOUBLE PRECISION NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "stockCount" BIGINT NULL DEFAULT 0,
  "supplierId" BIGINT NULL,
  "purchaseOrderId" BIGINT NULL,
  "purchaseOrderNo" VARCHAR NULL,
  deleted_at TIMESTAMPTZ NULL,
  deleted_by BIGINT NULL
);

-- 2.3 Capacity Net Price History
CREATE TABLE IF NOT EXISTS public.tblcapacity_netprice_history (
  id BIGSERIAL PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.tblproducts(id) ON DELETE CASCADE,
  capacity VARCHAR(100) NOT NULL,
  net_price NUMERIC(12, 2) NOT NULL,
  supplier_id BIGINT NULL,
  purchase_order_id BIGINT NULL,
  purchase_order_no VARCHAR(100) NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_netprice_history_lookup ON public.tblcapacity_netprice_history
  USING btree (product_id, capacity, supplier_id, purchase_order_id, purchase_order_no, id DESC);

-- ============================================================
-- SECTION 3: VENDORS & CUSTOMERS
-- ============================================================

-- 3.1 Vendors
CREATE TABLE IF NOT EXISTS public.tblvendors (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT NULL,
  contact_person TEXT NULL,
  contact_number TEXT NULL,
  last_order_date TIMESTAMPTZ NULL
);

-- 3.2 Customers
CREATE TABLE IF NOT EXISTS public.tblcustomer (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT NULL,
  contact_number TEXT NULL,
  email TEXT NULL,
  tin_number TEXT NULL,
  contact_person TEXT NULL,
  customer_type VARCHAR(20) DEFAULT 'regular' CHECK (customer_type IN ('regular', 'sub_dealer')),
  credit_limit NUMERIC(12, 2) DEFAULT 0,
  current_balance NUMERIC(12, 2) DEFAULT 0,
  payment_terms INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS idx_tblcustomer_type ON public.tblcustomer(customer_type);

-- ============================================================
-- SECTION 4: PURCHASE ORDERS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.tblpurchase_orders (
  id SERIAL PRIMARY KEY,
  po_number TEXT GENERATED ALWAYS AS ('PO-' || LPAD(id::TEXT, 6, '0')) STORED,
  vendor_id UUID NULL REFERENCES public.tblvendors(id),
  total_amount NUMERIC(12, 2) NULL DEFAULT 0,
  status TEXT NULL DEFAULT 'PENDING',
  po_type VARCHAR(20) DEFAULT 'ACU' CHECK (po_type IN ('ACU', 'MATERIAL')),
  created_at TIMESTAMPTZ NULL DEFAULT NOW(),
  created_by BIGINT NULL REFERENCES public.tblusers(id) ON UPDATE CASCADE ON DELETE SET NULL,
  "branchId" BIGINT NULL REFERENCES public.tblbranches(id) ON UPDATE CASCADE ON DELETE SET NULL,
  linked_sales_order_id INTEGER NULL
);

CREATE INDEX IF NOT EXISTS idx_tblpurchase_orders_po_type ON public.tblpurchase_orders(po_type);

-- ============================================================
-- SECTION 5: SALES ORDERS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.tblsales_order (
  id SERIAL PRIMARY KEY,
  so_number TEXT GENERATED ALWAYS AS ('SO-' || LPAD(id::TEXT, 6, '0')) STORED,
  customer_id UUID NULL REFERENCES public.tblcustomer(id) ON UPDATE CASCADE ON DELETE SET NULL,
  total_amount NUMERIC(12, 2) NULL DEFAULT 0,
  status TEXT NULL DEFAULT 'PENDING',
  created_at TIMESTAMPTZ NULL DEFAULT NOW(),
  created_by BIGINT NULL,
  "branchId" BIGINT NULL REFERENCES public.tblbranches(id) ON UPDATE CASCADE ON DELETE SET NULL,
  "scheduleDate" VARCHAR NULL,
  "salesType" VARCHAR NULL,
  remarks TEXT NULL,
  installer TEXT NULL,
  project_name TEXT NULL,
  project_code TEXT NULL,
  project_id BIGINT NULL,
  linked_purchase_order_id INTEGER NULL
);

CREATE INDEX IF NOT EXISTS idx_tblsales_order_project_id ON public.tblsales_order(project_id);

-- ============================================================
-- SECTION 6: TRANSACTION LINE ITEMS
-- ============================================================

-- 6.1 Product Transaction Items (SO/PO line items)
CREATE TABLE IF NOT EXISTS public.tbltransaction_product_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transType" VARCHAR NULL,
  "productId" BIGINT NULL REFERENCES public.tblproducts(id) ON UPDATE CASCADE ON DELETE SET NULL,
  "capacityId" BIGINT NULL REFERENCES public.tblcapacity(id) ON UPDATE CASCADE ON DELETE SET NULL,
  "unitPrice" DOUBLE PRECISION NULL,
  "sellPrice" DOUBLE PRECISION NULL,
  "discountPrice" DOUBLE PRECISION NULL,
  "unitTypesQty" JSONB NULL DEFAULT '[]'::jsonb,
  "scannedSerials" JSONB NULL DEFAULT '{}'::jsonb,
  "totalSetQty" BIGINT NULL,
  "purchaseId" INTEGER NULL REFERENCES public.tblpurchase_orders(id) ON UPDATE CASCADE ON DELETE SET NULL,
  "salesId" BIGINT NULL REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT tbltransaction_product_items_id_key UNIQUE (id)
);

-- 6.2 SO Material Items
CREATE TABLE IF NOT EXISTS public.tblso_material_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material_id BIGINT NULL,
  cost DOUBLE PRECISION NULL,
  price DOUBLE PRECISION NULL,
  "excessQty" BIGINT NULL,
  "usedQty" BIGINT NULL,
  "inclusionQty" BIGINT NULL,
  sales_id INTEGER NULL REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT tblso_material_items_id_key UNIQUE (id)
);

-- ============================================================
-- SECTION 7: SERIAL NUMBERS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.tblserial_numbers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branchId" BIGINT NULL REFERENCES public.tblbranches(id) ON UPDATE CASCADE ON DELETE SET NULL,
  "vendorId" UUID NULL REFERENCES public.tblvendors(id) ON UPDATE CASCADE ON DELETE SET NULL,
  "purchaseId" INTEGER NULL REFERENCES public.tblpurchase_orders(id) ON UPDATE CASCADE ON DELETE SET NULL,
  "previousPurchaseId" INTEGER NULL,
  "salesId" BIGINT NULL REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE SET NULL,
  "productId" BIGINT NULL REFERENCES public.tblproducts(id) ON UPDATE CASCADE ON DELETE SET NULL,
  "capacityId" BIGINT NULL REFERENCES public.tblcapacity(id) ON UPDATE CASCADE ON DELETE SET NULL,
  "serialNumber" VARCHAR NULL,
  "unitType" VARCHAR NULL,
  status VARCHAR NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT NULL REFERENCES public.tblusers(id) ON UPDATE CASCADE ON DELETE SET NULL,
  "customerId" UUID NULL REFERENCES public.tblcustomer(id) ON UPDATE CASCADE ON DELETE SET NULL,
  "previousSalesId" BIGINT NULL,
  "isDefective" BOOLEAN DEFAULT false,
  "isReturned" BOOLEAN DEFAULT false,
  "defectReason" TEXT NULL,
  "returnReason" TEXT NULL,
  "defectDate" TIMESTAMPTZ NULL,
  "returnDate" TIMESTAMPTZ NULL,
  CONSTRAINT tblserial_numbers_serialNumber_key UNIQUE ("serialNumber")
);

ALTER TABLE public.tblserial_numbers
  ADD CONSTRAINT tblserial_numbers_previousSalesId_fkey
  FOREIGN KEY ("previousSalesId") REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE public.tblserial_numbers
  ADD CONSTRAINT tblserial_numbers_previousPurchaseId_fkey
  FOREIGN KEY ("previousPurchaseId")
  REFERENCES public.tblpurchase_orders(id)
  ON UPDATE CASCADE
  ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_tblserial_numbers_isDefective ON public.tblserial_numbers("isDefective") WHERE "isDefective" = true;
CREATE INDEX IF NOT EXISTS idx_tblserial_numbers_isReturned ON public.tblserial_numbers("isReturned") WHERE "isReturned" = true;
CREATE INDEX IF NOT EXISTS idx_tblserial_numbers_previousPurchaseId ON public.tblserial_numbers("previousPurchaseId") WHERE "previousPurchaseId" IS NOT NULL;

-- ============================================================
-- SECTION 8: PAYMENTS
-- ============================================================

-- 8.1 PO Payments
CREATE TABLE IF NOT EXISTS public.tblpo_payments (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  po_id INTEGER NULL REFERENCES public.tblpurchase_orders(id),
  method TEXT NOT NULL,
  payment_date VARCHAR NULL,
  terms BIGINT NULL,
  "termsDueDate" VARCHAR NULL,
  status VARCHAR NULL,
  "paymentDate" VARCHAR NULL,
  "downPayment" NUMERIC NULL,
  bank_name TEXT NULL,
  reference_no TEXT NULL,
  check_no TEXT NULL,
  cheque_date TIMESTAMPTZ NULL,
  issued_by TEXT NULL
);

-- 8.2 SO Payments
CREATE TABLE IF NOT EXISTS public.tblso_payments (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  so_id INTEGER NULL REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE SET NULL,
  method TEXT NOT NULL,
  terms BIGINT NULL,
  "termsDueDate" VARCHAR NULL,
  status VARCHAR NULL,
  "paymentDate" VARCHAR NULL,
  "referenceNo" VARCHAR NULL,
  "issuedBy" VARCHAR NULL,
  "ccCharge" VARCHAR NULL,
  "checkNo" VARCHAR NULL,
  "bankName" VARCHAR NULL,
  "bankAccount" VARCHAR NULL,
  "downPayment" NUMERIC NULL,
  "postDated" VARCHAR NULL,
  payment_type VARCHAR(20) DEFAULT 'sales' CHECK (payment_type IN ('sales', 'expense')),
  amount NUMERIC(12, 2) DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_so_payments_type ON public.tblso_payments(payment_type);

-- 8.3 Customer Payments
CREATE TABLE IF NOT EXISTS public.tblcustomer_payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL REFERENCES public.tblcustomer(id) ON UPDATE CASCADE ON DELETE CASCADE,
  sales_id INTEGER REFERENCES public.tblsales_order(id),
  payment_amount NUMERIC(12, 2) NOT NULL,
  payment_date DATE NOT NULL,
  payment_method VARCHAR(50) NULL,
  reference_no VARCHAR(100) NULL,
  payment_notes TEXT NULL,
  applied_to_balance NUMERIC(12, 2) DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES public.tblusers(id)
);

CREATE INDEX IF NOT EXISTS idx_customer_payments_customer_id ON public.tblcustomer_payments(customer_id);
CREATE INDEX IF NOT EXISTS idx_customer_payments_sales_id ON public.tblcustomer_payments(sales_id);
CREATE INDEX IF NOT EXISTS idx_customer_payments_date ON public.tblcustomer_payments(payment_date);

-- ============================================================
-- SECTION 9: QUOTATIONS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.tblquotation (
  id BIGSERIAL PRIMARY KEY,
  quote_no TEXT NOT NULL UNIQUE,
  quote_date DATE NOT NULL DEFAULT CURRENT_DATE,
  customer_id UUID REFERENCES public.tblcustomer(id) ON DELETE SET NULL,
  customer_name TEXT NULL,
  customer_address TEXT NULL,
  customer_contact_person TEXT NULL,
  customer_contact_number TEXT NULL,
  customer_email TEXT NULL,
  customer_tin_number TEXT NULL,
  total_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'draft',
  remarks TEXT NULL,
  terms_conditions JSONB NOT NULL DEFAULT '{}'::jsonb,
  validity_days INTEGER NOT NULL DEFAULT 14,
  expires_at TIMESTAMPTZ NULL,
  expired_at TIMESTAMPTZ NULL,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_at TIMESTAMPTZ NULL,
  converted_sales_id BIGINT REFERENCES public.tblsales_order(id) ON DELETE SET NULL,
  created_by BIGINT REFERENCES public.tblusers(id) ON DELETE SET NULL,
  branch_id BIGINT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT tblquotation_status_check CHECK (LOWER(status) IN ('draft', 'finalized', 'converted', 'cancelled', 'expired'))
);

CREATE INDEX IF NOT EXISTS idx_tblquotation_customer_id ON public.tblquotation(customer_id);
CREATE INDEX IF NOT EXISTS idx_tblquotation_status ON public.tblquotation(status);
CREATE INDEX IF NOT EXISTS idx_tblquotation_quote_date ON public.tblquotation(quote_date);
CREATE INDEX IF NOT EXISTS idx_tblquotation_created_at ON public.tblquotation(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tblquotation_is_deleted ON public.tblquotation(is_deleted);
CREATE INDEX IF NOT EXISTS idx_tblquotation_expires_at ON public.tblquotation(expires_at);

CREATE TABLE IF NOT EXISTS public.tblquotation_items (
  id BIGSERIAL PRIMARY KEY,
  quotation_id BIGINT NOT NULL REFERENCES public.tblquotation(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.tblproducts(id) ON DELETE SET NULL,
  capacity_id BIGINT REFERENCES public.tblcapacity(id) ON DELETE SET NULL,
  unit_price NUMERIC(14, 2) NOT NULL DEFAULT 0,
  sell_price NUMERIC(14, 2) NOT NULL DEFAULT 0,
  discount_price NUMERIC(14, 2) NOT NULL DEFAULT 0,
  unit_types_qty JSONB NOT NULL DEFAULT '[]'::jsonb,
  total_set_qty INTEGER NOT NULL DEFAULT 0,
  line_total NUMERIC(14, 2) NOT NULL DEFAULT 0,
  remarks TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tblquotation_items_quotation_id ON public.tblquotation_items(quotation_id);
CREATE INDEX IF NOT EXISTS idx_tblquotation_items_product_id ON public.tblquotation_items(product_id);
CREATE INDEX IF NOT EXISTS idx_tblquotation_items_capacity_id ON public.tblquotation_items(capacity_id);

-- ============================================================
-- SECTION 10: PROJECTS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.tblprojects (
  id BIGSERIAL PRIMARY KEY,
  project_code VARCHAR(50) UNIQUE NOT NULL,
  project_name TEXT NOT NULL,
  project_type VARCHAR(50) NULL,
  project_owner TEXT NULL,
  project_owner_id BIGINT REFERENCES public.tblusers(id) ON DELETE SET NULL,
  project_location TEXT NULL,
  project_start_date DATE NULL,
  project_end_date DATE NULL,
  project_manager TEXT NULL,
  project_manager_id BIGINT REFERENCES public.tblusers(id) ON DELETE SET NULL,
  project_status VARCHAR(20) NOT NULL DEFAULT 'planning' CHECK (project_status IN ('planning', 'ongoing', 'completed', 'cancelled')),
  project_notes TEXT NULL,
  customer_id UUID NULL REFERENCES public.tblcustomer(id) ON UPDATE CASCADE ON DELETE SET NULL,
  poc_name TEXT NULL,
  poc_phone VARCHAR(50) NULL,
  poc_email VARCHAR(255) NULL,
  branch_id BIGINT NULL,
  created_by BIGINT REFERENCES public.tblusers(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tblprojects_project_code ON public.tblprojects(project_code);
CREATE INDEX IF NOT EXISTS idx_tblprojects_project_name ON public.tblprojects(project_name);
CREATE INDEX IF NOT EXISTS idx_tblprojects_project_status ON public.tblprojects(project_status);
CREATE INDEX IF NOT EXISTS idx_tblprojects_branch_id ON public.tblprojects(branch_id);
CREATE INDEX IF NOT EXISTS idx_tblprojects_project_owner_id ON public.tblprojects(project_owner_id);
CREATE INDEX IF NOT EXISTS idx_tblprojects_customer_id ON public.tblprojects(customer_id);

-- Add FK from sales_order to projects
ALTER TABLE public.tblsales_order
  ADD CONSTRAINT tblsales_order_project_id_fkey
  FOREIGN KEY (project_id) REFERENCES public.tblprojects(id) ON DELETE SET NULL;

-- Add FK from purchase_orders to sales_order (hybrid transfer)
ALTER TABLE public.tblpurchase_orders
  ADD CONSTRAINT tblpurchase_orders_linked_sales_order_id_fkey
  FOREIGN KEY (linked_sales_order_id) REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE public.tblsales_order
  ADD CONSTRAINT tblsales_order_linked_purchase_order_id_fkey
  FOREIGN KEY (linked_purchase_order_id) REFERENCES public.tblpurchase_orders(id) ON UPDATE CASCADE ON DELETE SET NULL;

-- ============================================================
-- SECTION 11: MATERIAL INVENTORY (Ledger-based)
-- ============================================================

-- 11.1 Material Items Catalog
CREATE TABLE IF NOT EXISTS public.tblmaterial_items (
  id BIGSERIAL PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  unit TEXT NOT NULL DEFAULT 'pcs',
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 11.2 Product-Capacity-Material BOM Map
CREATE TABLE IF NOT EXISTS public.tblproduct_capacity_material_map (
  id BIGSERIAL PRIMARY KEY,
  product_id BIGINT NOT NULL,
  capacity_id BIGINT NOT NULL,
  material_id BIGINT NOT NULL REFERENCES public.tblmaterial_items(id),
  qty_per_set NUMERIC(14, 4) NOT NULL DEFAULT 1,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(product_id, capacity_id, material_id)
);

-- 11.3 Material Stock Balance
CREATE TABLE IF NOT EXISTS public.tblmaterial_stock_balance (
  id BIGSERIAL PRIMARY KEY,
  material_id BIGINT NOT NULL REFERENCES public.tblmaterial_items(id),
  on_hand NUMERIC(14, 2) NOT NULL DEFAULT 0,
  reserved NUMERIC(14, 2) NOT NULL DEFAULT 0,
  available NUMERIC(14, 2) GENERATED ALWAYS AS (on_hand - reserved) STORED,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(material_id)
);

-- 11.4 Material Stock Movement Ledger
CREATE TABLE IF NOT EXISTS public.tblmaterial_stock_movement (
  id BIGSERIAL PRIMARY KEY,
  material_id BIGINT NOT NULL REFERENCES public.tblmaterial_items(id),
  movement_type TEXT NOT NULL CHECK (movement_type IN ('IN', 'OUT', 'RESERVE', 'RELEASE', 'RETURN', 'ADJUST')),
  qty NUMERIC(14, 2) NOT NULL CHECK (qty > 0),
  source_type TEXT NOT NULL CHECK (source_type IN ('PO', 'SO', 'MANUAL')),
  source_id BIGINT NOT NULL,
  source_line_key TEXT NOT NULL,
  status_snapshot TEXT NULL,
  remarks TEXT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(source_type, source_id, movement_type, source_line_key)
);

CREATE INDEX IF NOT EXISTS idx_material_stock_movement_source ON public.tblmaterial_stock_movement(source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_material_stock_movement_material ON public.tblmaterial_stock_movement(material_id, created_at DESC);

-- 11.5 Materials (Product-level material inventory)
CREATE TABLE IF NOT EXISTS public.tblmaterials (
  id BIGSERIAL PRIMARY KEY,
  brand_id BIGINT NULL REFERENCES public.tblbrands(id) ON UPDATE CASCADE ON DELETE SET NULL,
  material_name TEXT NOT NULL,
  material_code VARCHAR(50) UNIQUE,
  description TEXT NULL,
  unit VARCHAR(20) DEFAULT 'PCS',
  unit_price NUMERIC(12, 2) DEFAULT 0,
  sell_price NUMERIC(12, 2) DEFAULT 0,
  on_hand_stock BIGINT DEFAULT 0,
  reorder_level BIGINT DEFAULT 0,
  category VARCHAR(50) NOT NULL DEFAULT 'general'
    CHECK (category IN ('excess', 'electrical', 'material', 'general')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES public.tblusers(id) ON UPDATE CASCADE ON DELETE SET NULL,
  updated_at TIMESTAMPTZ NULL,
  updated_by BIGINT REFERENCES public.tblusers(id) ON UPDATE CASCADE ON DELETE SET NULL,
  deleted_at TIMESTAMPTZ NULL,
  deleted_by BIGINT REFERENCES public.tblusers(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT tblmaterials_material_name_key UNIQUE (material_name)
);

CREATE INDEX IF NOT EXISTS idx_tblmaterials_brand_id ON public.tblmaterials(brand_id);
CREATE INDEX IF NOT EXISTS idx_tblmaterials_deleted_at ON public.tblmaterials(deleted_at);
CREATE INDEX IF NOT EXISTS idx_tblmaterials_on_hand_stock ON public.tblmaterials(on_hand_stock);
CREATE INDEX IF NOT EXISTS idx_tblmaterials_category ON public.tblmaterials(category);

-- 11.6 Material Price History
CREATE TABLE IF NOT EXISTS public.tblmaterial_price_history (
  id BIGSERIAL PRIMARY KEY,
  material_id BIGINT NOT NULL REFERENCES public.tblmaterials(id) ON DELETE CASCADE,
  unit_price NUMERIC(12, 2) NOT NULL,
  sell_price NUMERIC(12, 2) NOT NULL,
  supplier_id UUID REFERENCES public.tblvendors(id),
  purchase_order_id INTEGER REFERENCES public.tblpurchase_orders(id),
  purchase_order_no VARCHAR(100) NULL,
  created_by BIGINT REFERENCES public.tblusers(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_material_price_history_lookup ON public.tblmaterial_price_history(material_id, id DESC);

-- 11.7 Material Transaction Items
CREATE TABLE IF NOT EXISTS public.tbltransaction_material_items (
  id BIGSERIAL PRIMARY KEY,
  trans_type VARCHAR(20) NOT NULL CHECK (trans_type IN ('purchase', 'sales')),
  material_id BIGINT NOT NULL REFERENCES public.tblmaterials(id) ON UPDATE CASCADE ON DELETE CASCADE,
  quantity BIGINT NOT NULL DEFAULT 0,
  unit_price NUMERIC(12, 2) DEFAULT 0,
  sell_price NUMERIC(12, 2) DEFAULT 0,
  discount_price NUMERIC(12, 2) DEFAULT 0,
  purchase_id INTEGER REFERENCES public.tblpurchase_orders(id) ON UPDATE CASCADE ON DELETE CASCADE,
  sales_id INTEGER REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_transaction_material_purchase ON public.tbltransaction_material_items(purchase_id);
CREATE INDEX IF NOT EXISTS idx_transaction_material_sales ON public.tbltransaction_material_items(sales_id);
CREATE INDEX IF NOT EXISTS idx_transaction_material_material_id ON public.tbltransaction_material_items(material_id);

-- 11.8 SO Miscellaneous Items
CREATE TABLE IF NOT EXISTS public.tblso_miscellaneous_items (
  id BIGSERIAL PRIMARY KEY,
  sales_id INTEGER NOT NULL REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
  category VARCHAR(50) NOT NULL DEFAULT 'general'
    CHECK (category IN ('excess', 'electrical', 'material', 'general')),
  item_name TEXT NOT NULL,
  description TEXT NULL,
  material_id BIGINT NULL REFERENCES public.tblmaterial_items(id) ON DELETE SET NULL,
  quantity NUMERIC(12, 2) NOT NULL DEFAULT 1,
  unit VARCHAR(20) DEFAULT 'pcs',
  unit_price NUMERIC(12, 2) DEFAULT 0,
  total_price NUMERIC(12, 2) DEFAULT 0,
  is_inclusion BOOLEAN DEFAULT false,
  remarks TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_so_misc_items_sales_id ON public.tblso_miscellaneous_items(sales_id);
CREATE INDEX IF NOT EXISTS idx_so_misc_items_category ON public.tblso_miscellaneous_items(category);
CREATE INDEX IF NOT EXISTS idx_so_misc_items_material_id ON public.tblso_miscellaneous_items(material_id);

-- ============================================================
-- SECTION 12: SALES ORDER EXTENDED TABLES
-- ============================================================

-- 12.1 Project Details (per SO)
CREATE TABLE IF NOT EXISTS public.tblproject_details (
  id BIGSERIAL PRIMARY KEY,
  sales_id INTEGER NOT NULL REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
  project_name TEXT NOT NULL,
  project_code VARCHAR(50) UNIQUE,
  project_location TEXT NULL,
  project_start_date DATE NULL,
  project_end_date DATE NULL,
  project_manager TEXT NULL,
  project_status VARCHAR(20) DEFAULT 'ongoing' CHECK (project_status IN ('planning', 'ongoing', 'completed', 'cancelled')),
  project_notes TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NULL,
  CONSTRAINT tblproject_details_sales_id_key UNIQUE (sales_id)
);

CREATE INDEX IF NOT EXISTS idx_project_details_sales_id ON public.tblproject_details(sales_id);
CREATE INDEX IF NOT EXISTS idx_project_details_status ON public.tblproject_details(project_status);

-- 12.2 Service Details
CREATE TABLE IF NOT EXISTS public.tblservice_details (
  id BIGSERIAL PRIMARY KEY,
  sales_id INTEGER NOT NULL REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
  service_name TEXT NOT NULL,
  service_description TEXT NULL,
  service_type VARCHAR(50) NULL,
  technician_assigned TEXT NULL,
  service_date DATE NULL,
  service_duration_hours NUMERIC(5, 2) NULL,
  service_cost NUMERIC(12, 2) DEFAULT 0,
  parts_cost NUMERIC(12, 2) DEFAULT 0,
  labor_cost NUMERIC(12, 2) DEFAULT 0,
  service_status VARCHAR(20) DEFAULT 'scheduled' CHECK (service_status IN ('scheduled', 'in_progress', 'completed', 'cancelled')),
  service_notes TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS idx_service_details_sales_id ON public.tblservice_details(sales_id);
CREATE INDEX IF NOT EXISTS idx_service_details_status ON public.tblservice_details(service_status);
CREATE INDEX IF NOT EXISTS idx_service_details_date ON public.tblservice_details(service_date);

-- 12.3 Concern Details
CREATE TABLE IF NOT EXISTS public.tblconcern_details (
  id BIGSERIAL PRIMARY KEY,
  sales_id INTEGER REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
  customer_id UUID REFERENCES public.tblcustomer(id) ON UPDATE CASCADE ON DELETE CASCADE,
  concern_type VARCHAR(50) NULL,
  concern_subject TEXT NOT NULL,
  concern_description TEXT NOT NULL,
  concern_status VARCHAR(20) DEFAULT 'open' CHECK (concern_status IN (
    'open', 'in_progress', 'resolved', 'closed',
    'in-progress', 'reschedule', 'pulled-out', 'warranty', 'void-warranty', 'complete', ''
  )),
  priority VARCHAR(20) DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  assigned_to BIGINT REFERENCES public.tblusers(id),
  resolution_notes TEXT NULL,
  resolved_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS idx_concern_details_sales_id ON public.tblconcern_details(sales_id);
CREATE INDEX IF NOT EXISTS idx_concern_details_customer_id ON public.tblconcern_details(customer_id);
CREATE INDEX IF NOT EXISTS idx_concern_details_status ON public.tblconcern_details(concern_status);

-- 12.4 Transfer Details (branch-to-branch)
CREATE TABLE IF NOT EXISTS public.tbltransfer_details (
  id BIGSERIAL PRIMARY KEY,
  sales_id INTEGER NOT NULL REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
  from_branch_id BIGINT NOT NULL REFERENCES public.tblbranches(id),
  to_branch_id BIGINT NOT NULL REFERENCES public.tblbranches(id),
  transfer_date DATE NULL,
  expected_delivery_date DATE NULL,
  actual_delivery_date DATE NULL,
  transfer_status VARCHAR(20) DEFAULT 'pending' CHECK (transfer_status IN ('pending', 'in_transit', 'delivered', 'acknowledged', 'cancelled')),
  sent_by BIGINT REFERENCES public.tblusers(id),
  received_by BIGINT REFERENCES public.tblusers(id),
  acknowledged_by BIGINT REFERENCES public.tblusers(id),
  acknowledged_at TIMESTAMPTZ NULL,
  transfer_notes TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NULL,
  CONSTRAINT tbltransfer_details_sales_id_key UNIQUE (sales_id)
);

CREATE INDEX IF NOT EXISTS idx_transfer_details_from_branch ON public.tbltransfer_details(from_branch_id);
CREATE INDEX IF NOT EXISTS idx_transfer_details_to_branch ON public.tbltransfer_details(to_branch_id);
CREATE INDEX IF NOT EXISTS idx_transfer_details_status ON public.tbltransfer_details(transfer_status);

-- 12.5 Expense Details
CREATE TABLE IF NOT EXISTS public.tblexpense_details (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sales_id INTEGER REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
  transfer_id BIGINT REFERENCES public.tbltransfer_details(id) ON UPDATE CASCADE ON DELETE CASCADE,
  expense_type VARCHAR(50) NOT NULL,
  expense_description TEXT NULL,
  amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  expense_date DATE NULL,
  paid_to TEXT NULL,
  payment_method VARCHAR(50) NULL,
  reference_no VARCHAR(100) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES public.tblusers(id)
);

CREATE INDEX IF NOT EXISTS idx_expense_details_sales_id ON public.tblexpense_details(sales_id);
CREATE INDEX IF NOT EXISTS idx_expense_details_transfer_id ON public.tblexpense_details(transfer_id);

-- 12.6 Statement of Account
CREATE TABLE IF NOT EXISTS public.tblstatement_of_account (
  id BIGSERIAL PRIMARY KEY,
  soa_number TEXT GENERATED ALWAYS AS ('SOA-' || LPAD(id::TEXT, 6, '0')) STORED,
  customer_id UUID NOT NULL REFERENCES public.tblcustomer(id) ON UPDATE CASCADE ON DELETE CASCADE,
  project_id BIGINT NULL REFERENCES public.tblprojects(id) ON UPDATE CASCADE ON DELETE SET NULL,
  period_from DATE NOT NULL,
  period_to DATE NOT NULL,
  opening_balance NUMERIC(12, 2) DEFAULT 0,
  total_charges NUMERIC(12, 2) DEFAULT 0,
  total_payments NUMERIC(12, 2) DEFAULT 0,
  closing_balance NUMERIC(12, 2) DEFAULT 0,
  soa_status VARCHAR(20) DEFAULT 'draft' CHECK (soa_status IN ('draft', 'sent', 'paid', 'overdue')),
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  generated_by BIGINT REFERENCES public.tblusers(id),
  sent_at TIMESTAMPTZ NULL,
  due_date DATE NULL,
  notes TEXT NULL
);

CREATE INDEX IF NOT EXISTS idx_soa_customer_id ON public.tblstatement_of_account(customer_id);
CREATE INDEX IF NOT EXISTS idx_soa_status ON public.tblstatement_of_account(soa_status);
CREATE INDEX IF NOT EXISTS idx_soa_period ON public.tblstatement_of_account(period_from, period_to);
CREATE INDEX IF NOT EXISTS idx_soa_project_id ON public.tblstatement_of_account(project_id)
  WHERE project_id IS NOT NULL;

-- ============================================================
-- SECTION 13: ACCOUNTING
-- ============================================================

-- 13.1 Account Titles (Chart of Accounts)
CREATE TABLE IF NOT EXISTS public.tblaccount_titles (
  id BIGSERIAL PRIMARY KEY,
  account_number VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tblaccount_titles_number_description
  ON public.tblaccount_titles (account_number, description);

-- 13.2 Cheque Vouchers (Live workflow)
CREATE TABLE IF NOT EXISTS public.tblcheque_vouchers (
  id BIGSERIAL PRIMARY KEY,
  cv_no VARCHAR(32) NOT NULL UNIQUE,
  voucher_type VARCHAR(120) NOT NULL,
  payee TEXT NOT NULL DEFAULT '',
  voucher_date DATE NOT NULL,
  tin_number TEXT NULL,
  address TEXT NULL,
  zip_code TEXT NULL,
  particulars TEXT NULL,
  prepared_by TEXT NULL,
  released_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tblcheque_vouchers_voucher_date ON public.tblcheque_vouchers(voucher_date);

-- 13.3 Cheque Voucher Deposits
CREATE TABLE IF NOT EXISTS public.tblcheque_voucher_deposits (
  id BIGSERIAL PRIMARY KEY,
  voucher_id BIGINT NOT NULL REFERENCES public.tblcheque_vouchers(id) ON DELETE CASCADE,
  bank_name TEXT NULL,
  cheque_no TEXT NULL,
  cheque_date DATE NULL,
  amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tblcheque_voucher_deposits_voucher_id ON public.tblcheque_voucher_deposits(voucher_id);

-- 13.4 Cheque Voucher Invoices
CREATE TABLE IF NOT EXISTS public.tblcheque_voucher_invoices (
  id BIGSERIAL PRIMARY KEY,
  voucher_id BIGINT NOT NULL REFERENCES public.tblcheque_vouchers(id) ON DELETE CASCADE,
  invoice_no TEXT NULL,
  invoice_date DATE NULL,
  description TEXT NULL,
  amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tblcheque_voucher_invoices_voucher_id ON public.tblcheque_voucher_invoices(voucher_id);

-- 13.5 Cheque Voucher Account Titles (debit/credit entries)
CREATE TABLE IF NOT EXISTS public.tblcheque_voucher_account_titles (
  id BIGSERIAL PRIMARY KEY,
  voucher_id BIGINT NOT NULL REFERENCES public.tblcheque_vouchers(id) ON DELETE CASCADE,
  account_title_id BIGINT REFERENCES public.tblaccount_titles(id),
  account_number VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  debit NUMERIC(14, 2) NOT NULL DEFAULT 0,
  credit NUMERIC(14, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tblcheque_voucher_account_titles_voucher_id ON public.tblcheque_voucher_account_titles(voucher_id);

-- 13.6 Cheque Voucher (Legacy/simple version)
CREATE TABLE IF NOT EXISTS public.tblcheque_voucher (
  id BIGSERIAL PRIMARY KEY,
  cv_number TEXT GENERATED ALWAYS AS ('CV-' || LPAD(id::TEXT, 6, '0')) STORED,
  payee_name TEXT NOT NULL,
  payee_address TEXT NULL,
  payee_tin VARCHAR(50) NULL,
  cheque_number VARCHAR(50) NULL,
  bank_name VARCHAR(100) NULL,
  cheque_date DATE NULL,
  amount NUMERIC(12, 2) NOT NULL,
  amount_in_words TEXT NULL,
  particulars TEXT NOT NULL,
  account_code VARCHAR(50) NULL,
  category VARCHAR(50) NULL,
  payment_type VARCHAR(50) NULL,
  status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'approved', 'issued', 'cleared', 'cancelled')),
  approved_by BIGINT REFERENCES public.tblusers(id),
  approved_at TIMESTAMPTZ NULL,
  issued_by BIGINT REFERENCES public.tblusers(id),
  issued_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES public.tblusers(id),
  updated_at TIMESTAMPTZ NULL,
  updated_by BIGINT REFERENCES public.tblusers(id)
);

CREATE INDEX IF NOT EXISTS idx_cheque_voucher_status ON public.tblcheque_voucher(status);
CREATE INDEX IF NOT EXISTS idx_cheque_voucher_date ON public.tblcheque_voucher(cheque_date);
CREATE INDEX IF NOT EXISTS idx_cheque_voucher_payee ON public.tblcheque_voucher(payee_name);

-- 13.7 General Journal
CREATE TABLE IF NOT EXISTS public.tblgeneral_journal (
  id BIGSERIAL PRIMARY KEY,
  journal_number TEXT GENERATED ALWAYS AS ('JE-' || LPAD(id::TEXT, 6, '0')) STORED,
  journal_date DATE NOT NULL,
  reference_type VARCHAR(50) NULL,
  reference_id INTEGER NULL,
  reference_number TEXT NULL,
  description TEXT NOT NULL,
  total_debit NUMERIC(12, 2) DEFAULT 0,
  total_credit NUMERIC(12, 2) DEFAULT 0,
  status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'posted', 'reversed')),
  posted_at TIMESTAMPTZ NULL,
  posted_by BIGINT REFERENCES public.tblusers(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES public.tblusers(id)
);

CREATE INDEX IF NOT EXISTS idx_general_journal_date ON public.tblgeneral_journal(journal_date);
CREATE INDEX IF NOT EXISTS idx_general_journal_status ON public.tblgeneral_journal(status);
CREATE INDEX IF NOT EXISTS idx_general_journal_reference ON public.tblgeneral_journal(reference_type, reference_id);

-- 13.8 Journal Entry Lines
CREATE TABLE IF NOT EXISTS public.tbljournal_entry_lines (
  id BIGSERIAL PRIMARY KEY,
  journal_id BIGINT NOT NULL REFERENCES public.tblgeneral_journal(id) ON DELETE CASCADE,
  line_number INTEGER NOT NULL,
  account_code VARCHAR(50) NOT NULL,
  account_name TEXT NOT NULL,
  description TEXT NULL,
  debit_amount NUMERIC(12, 2) DEFAULT 0,
  credit_amount NUMERIC(12, 2) DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_journal_lines_journal_id ON public.tbljournal_entry_lines(journal_id);
CREATE INDEX IF NOT EXISTS idx_journal_lines_account ON public.tbljournal_entry_lines(account_code);

-- 13.9 Tax 2307 Report
CREATE TABLE IF NOT EXISTS public.tbltax_2307 (
  id BIGSERIAL PRIMARY KEY,
  tax_year INTEGER NOT NULL,
  tax_quarter INTEGER CHECK (tax_quarter BETWEEN 1 AND 4),
  tax_month INTEGER CHECK (tax_month BETWEEN 1 AND 12),
  payee_name TEXT NOT NULL,
  payee_tin VARCHAR(50) NOT NULL,
  payee_address TEXT NULL,
  income_payment_type VARCHAR(100) NULL,
  atc_code VARCHAR(10) NULL,
  gross_amount NUMERIC(12, 2) NOT NULL,
  tax_rate NUMERIC(5, 2) NOT NULL,
  tax_withheld NUMERIC(12, 2) NOT NULL,
  payment_date DATE NULL,
  reference_type VARCHAR(50) NULL,
  reference_id INTEGER NULL,
  reference_number TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES public.tblusers(id)
);

CREATE INDEX IF NOT EXISTS idx_tax_2307_year_quarter ON public.tbltax_2307(tax_year, tax_quarter);
CREATE INDEX IF NOT EXISTS idx_tax_2307_payee_tin ON public.tbltax_2307(payee_tin);
CREATE INDEX IF NOT EXISTS idx_tax_2307_date ON public.tbltax_2307(payment_date);

-- 13.10 Accounting Report Print Settings
CREATE TABLE IF NOT EXISTS public.tblaccounting_report_print_settings (
  id BIGSERIAL PRIMARY KEY,
  report_key TEXT NOT NULL,
  branch_id BIGINT NOT NULL DEFAULT 0,
  settings_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by BIGINT NULL,
  updated_by BIGINT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tblaccounting_report_print_settings_report_branch
  ON public.tblaccounting_report_print_settings (report_key, branch_id);
CREATE INDEX IF NOT EXISTS idx_tblaccounting_report_print_settings_report_key
  ON public.tblaccounting_report_print_settings (report_key);
CREATE INDEX IF NOT EXISTS idx_tblaccounting_report_print_settings_branch_id
  ON public.tblaccounting_report_print_settings (branch_id);

-- ============================================================
-- SECTION 14: RBAC (Normalized Permission System)
-- ============================================================

-- 14.1 Permission Dictionary
CREATE TABLE IF NOT EXISTS public.auth_permission_keys (
  id BIGSERIAL PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  module TEXT NOT NULL,
  scope TEXT NOT NULL DEFAULT 'feature',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT auth_permission_keys_scope_check CHECK (scope IN ('feature', 'menu', 'tab', 'action'))
);

-- 14.2 Role -> Permission Mapping
CREATE TABLE IF NOT EXISTS public.auth_role_permissions (
  id BIGSERIAL PRIMARY KEY,
  role_id BIGINT NOT NULL REFERENCES public.tblrbac(id) ON DELETE CASCADE,
  permission_id BIGINT NOT NULL REFERENCES public.auth_permission_keys(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(role_id, permission_id)
);

CREATE INDEX IF NOT EXISTS idx_auth_role_permissions_role_id ON public.auth_role_permissions(role_id);
CREATE INDEX IF NOT EXISTS idx_auth_role_permissions_permission_id ON public.auth_role_permissions(permission_id);

-- 14.3 User-level Permission Overrides
CREATE TABLE IF NOT EXISTS public.auth_user_permission_overrides (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.tblusers(id) ON DELETE CASCADE,
  permission_id BIGINT NOT NULL REFERENCES public.auth_permission_keys(id) ON DELETE CASCADE,
  effect TEXT NOT NULL,
  reason TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT auth_user_permission_overrides_effect_check CHECK (effect IN ('allow', 'deny')),
  UNIQUE(user_id, permission_id)
);

CREATE INDEX IF NOT EXISTS idx_auth_user_permission_overrides_user_id ON public.auth_user_permission_overrides(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_user_permission_overrides_permission_id ON public.auth_user_permission_overrides(permission_id);

-- 14.4 User-Role Assignment
CREATE TABLE IF NOT EXISTS public.auth_user_roles (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.tblusers(id) ON DELETE CASCADE,
  role_id BIGINT NOT NULL REFERENCES public.tblrbac(id) ON DELETE CASCADE,
  is_primary BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, role_id)
);

CREATE INDEX IF NOT EXISTS idx_auth_user_roles_user_id ON public.auth_user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_user_roles_role_id ON public.auth_user_roles(role_id);

-- 14.5 Menu Registry
CREATE TABLE IF NOT EXISTS public.auth_menus (
  id BIGSERIAL PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  parent_key TEXT NULL,
  route TEXT NULL,
  icon TEXT NULL,
  order_no INT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- SECTION 15: AUDIT & PROCESS
-- ============================================================

-- 15.1 Audit Logs
CREATE TABLE IF NOT EXISTS public.tblaudit_logs (
  id BIGSERIAL PRIMARY KEY,
  action VARCHAR(100) NOT NULL,
  entity_type VARCHAR(100) NOT NULL,
  entity_id VARCHAR(100) NULL,
  user_id INTEGER NULL,
  username VARCHAR(150) NULL,
  role_name VARCHAR(100) NULL,
  branch_id INTEGER NULL,
  ip_address VARCHAR(60) NULL,
  metadata JSONB NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON public.tblaudit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON public.tblaudit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON public.tblaudit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON public.tblaudit_logs(created_at DESC);

-- 15.2 Audit Log (detailed change tracking)
CREATE TABLE IF NOT EXISTS public.tblaudit_log (
  id BIGSERIAL PRIMARY KEY,
  table_name VARCHAR(100) NOT NULL,
  record_id TEXT NOT NULL,
  action VARCHAR(20) NOT NULL CHECK (action IN ('CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'CANCEL')),
  old_values JSONB NULL,
  new_values JSONB NULL,
  changed_by BIGINT REFERENCES public.tblusers(id),
  changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ip_address VARCHAR(50) NULL,
  user_agent TEXT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_log_table_record ON public.tblaudit_log(table_name, record_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_changed_by ON public.tblaudit_log(changed_by);
CREATE INDEX IF NOT EXISTS idx_audit_log_changed_at ON public.tblaudit_log(changed_at);

-- 15.3 Serial Number Events (Immutable Event Log)
CREATE TABLE IF NOT EXISTS public.tblserial_number_events (
  id BIGSERIAL PRIMARY KEY,
  serial_id BIGINT NOT NULL REFERENCES public.tblserial_numbers(id) ON DELETE CASCADE,
  serial_number VARCHAR NOT NULL,

  event_type VARCHAR(50) NOT NULL,

  previous_status VARCHAR(50) NULL,
  new_status VARCHAR(50) NULL,

  previous_purchase_id INTEGER NULL,
  new_purchase_id INTEGER NULL,
  previous_sales_id INTEGER NULL,
  new_sales_id INTEGER NULL,
  previous_branch_id BIGINT NULL,
  new_branch_id BIGINT NULL,
  previous_customer_id UUID NULL,
  new_customer_id UUID NULL,

  performed_by BIGINT NULL REFERENCES public.tblusers(id),
  performed_by_username VARCHAR(150) NULL,
  ip_address VARCHAR(60) NULL,

  reason TEXT NULL,
  metadata JSONB NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_serial_events_serial_id ON public.tblserial_number_events(serial_id);
CREATE INDEX IF NOT EXISTS idx_serial_events_serial_number ON public.tblserial_number_events(serial_number);
CREATE INDEX IF NOT EXISTS idx_serial_events_event_type ON public.tblserial_number_events(event_type);
CREATE INDEX IF NOT EXISTS idx_serial_events_purchase_id ON public.tblserial_number_events(new_purchase_id);
CREATE INDEX IF NOT EXISTS idx_serial_events_sales_id ON public.tblserial_number_events(new_sales_id);
CREATE INDEX IF NOT EXISTS idx_serial_events_created_at ON public.tblserial_number_events(created_at DESC);

-- 15.4 Process Flow
CREATE TABLE IF NOT EXISTS public.tblprocessflow (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status VARCHAR NULL,
  "nextStep" TEXT NULL,
  "processedBy" BIGINT NULL,
  "stepNo" INTEGER NULL,
  "stepStatus" TEXT NULL,
  "actionStatus" JSON NULL,
  "actionList" JSON NULL
);

-- 15.5 Installation
CREATE TABLE IF NOT EXISTS public.tblinstallation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  installer_id BIGINT NULL,
  members JSONB NULL DEFAULT '[]'::jsonb,
  "workDone" TEXT NULL,
  CONSTRAINT tblinstallation_id_key UNIQUE (id)
);

-- ============================================================
-- SECTION 16: FUNCTIONS & TRIGGERS
-- ============================================================

-- 16.1 Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION public.set_current_timestamp_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- Apply updated_at triggers
DROP TRIGGER IF EXISTS trg_auth_permission_keys_updated_at ON public.auth_permission_keys;
CREATE TRIGGER trg_auth_permission_keys_updated_at
  BEFORE UPDATE ON public.auth_permission_keys
  FOR EACH ROW EXECUTE FUNCTION public.set_current_timestamp_updated_at();

DROP TRIGGER IF EXISTS trg_auth_user_permission_overrides_updated_at ON public.auth_user_permission_overrides;
CREATE TRIGGER trg_auth_user_permission_overrides_updated_at
  BEFORE UPDATE ON public.auth_user_permission_overrides
  FOR EACH ROW EXECUTE FUNCTION public.set_current_timestamp_updated_at();

DROP TRIGGER IF EXISTS trg_tblquotation_updated_at ON public.tblquotation;
CREATE TRIGGER trg_tblquotation_updated_at
  BEFORE UPDATE ON public.tblquotation
  FOR EACH ROW EXECUTE FUNCTION public.set_current_timestamp_updated_at();

DROP TRIGGER IF EXISTS trg_tblquotation_items_updated_at ON public.tblquotation_items;
CREATE TRIGGER trg_tblquotation_items_updated_at
  BEFORE UPDATE ON public.tblquotation_items
  FOR EACH ROW EXECUTE FUNCTION public.set_current_timestamp_updated_at();

DROP TRIGGER IF EXISTS trg_tblprojects_updated_at ON public.tblprojects;
CREATE TRIGGER trg_tblprojects_updated_at
  BEFORE UPDATE ON public.tblprojects
  FOR EACH ROW EXECUTE FUNCTION public.set_current_timestamp_updated_at();

-- 16.2 Quotation auto-generate quote_no
CREATE OR REPLACE FUNCTION public.tblquotation_set_quote_no()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.id IS NULL THEN
    NEW.id := nextval(pg_get_serial_sequence('public.tblquotation', 'id'));
  END IF;

  IF NEW.quote_no IS NULL OR btrim(NEW.quote_no) = '' THEN
    NEW.quote_no :=
      'QT-' ||
      to_char(COALESCE(NEW.quote_date, CURRENT_DATE), 'YYYYMMDD') ||
      '-' ||
      lpad(NEW.id::text, 6, '0');
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_tblquotation_set_quote_no ON public.tblquotation;
CREATE TRIGGER trg_tblquotation_set_quote_no
  BEFORE INSERT ON public.tblquotation
  FOR EACH ROW EXECUTE FUNCTION public.tblquotation_set_quote_no();

-- 16.3 Material stock update on PO approval
CREATE OR REPLACE FUNCTION public.update_material_stock_on_po_approval()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'APPROVED' AND OLD.status != 'APPROVED' AND NEW.po_type = 'MATERIAL' THEN
    UPDATE public.tblmaterials m
    SET on_hand_stock = on_hand_stock + tmi.quantity,
        updated_at = NOW()
    FROM public.tbltransaction_material_items tmi
    WHERE tmi.purchase_id = NEW.id
      AND tmi.material_id = m.id
      AND tmi.trans_type = 'purchase';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_material_stock_on_po_approval ON public.tblpurchase_orders;
CREATE TRIGGER trg_update_material_stock_on_po_approval
  AFTER UPDATE ON public.tblpurchase_orders
  FOR EACH ROW EXECUTE FUNCTION public.update_material_stock_on_po_approval();

-- 16.4 Customer balance recalculation
CREATE OR REPLACE FUNCTION public.recalc_customer_balance(p_customer_id UUID)
RETURNS VOID AS $$
BEGIN
  UPDATE public.tblcustomer
  SET current_balance = (
    COALESCE((SELECT SUM(total_amount) FROM public.tblsales_order WHERE customer_id = p_customer_id), 0)
    - COALESCE((SELECT SUM(payment_amount) FROM public.tblcustomer_payments WHERE customer_id = p_customer_id), 0)
    - COALESCE((
        SELECT SUM(COALESCE(sp.amount, 0))
        FROM public.tblso_payments sp
        JOIN public.tblsales_order so ON so.id = sp.so_id
        WHERE so.customer_id = p_customer_id
          AND LOWER(COALESCE(sp.status, 'paid')) = 'paid'
          AND LOWER(COALESCE(sp.payment_type, 'sales')) = 'sales'
      ), 0)
  ),
  updated_at = NOW()
  WHERE id = p_customer_id;
END;
$$ LANGUAGE plpgsql;

-- Trigger: recalc balance on sales order change
CREATE OR REPLACE FUNCTION public.update_customer_balance_on_sales()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.customer_id IS NOT NULL THEN
    PERFORM public.recalc_customer_balance(NEW.customer_id);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_customer_balance_on_sales ON public.tblsales_order;
CREATE TRIGGER trg_update_customer_balance_on_sales
  AFTER INSERT OR UPDATE ON public.tblsales_order
  FOR EACH ROW EXECUTE FUNCTION public.update_customer_balance_on_sales();

-- Trigger: recalc balance on customer payment
CREATE OR REPLACE FUNCTION public.update_customer_balance_on_customer_payment()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.customer_id IS NOT NULL THEN
    PERFORM public.recalc_customer_balance(NEW.customer_id);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_customer_balance_on_payment ON public.tblcustomer_payments;
CREATE TRIGGER trg_update_customer_balance_on_payment
  AFTER INSERT OR UPDATE ON public.tblcustomer_payments
  FOR EACH ROW EXECUTE FUNCTION public.update_customer_balance_on_customer_payment();

-- Trigger: recalc balance on SO payment
CREATE OR REPLACE FUNCTION public.update_customer_balance_on_so_payment()
RETURNS TRIGGER AS $$
DECLARE
  v_customer_id UUID;
BEGIN
  SELECT customer_id INTO v_customer_id FROM public.tblsales_order WHERE id = NEW.so_id;
  IF v_customer_id IS NOT NULL THEN
    PERFORM public.recalc_customer_balance(v_customer_id);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_customer_balance_on_so_payment ON public.tblso_payments;
CREATE TRIGGER trg_update_customer_balance_on_so_payment
  AFTER INSERT OR UPDATE ON public.tblso_payments
  FOR EACH ROW EXECUTE FUNCTION public.update_customer_balance_on_so_payment();

-- ============================================================
-- SECTION 17: VIEWS
-- ============================================================

-- Effective permissions view (resolves role grants + user overrides)
CREATE OR REPLACE VIEW public.v_auth_user_effective_permissions AS
WITH role_grants AS (
  SELECT
    ur.user_id,
    rp.permission_id,
    TRUE AS granted_by_role
  FROM public.auth_user_roles ur
  JOIN public.auth_role_permissions rp ON rp.role_id = ur.role_id
), user_overrides AS (
  SELECT
    user_id,
    permission_id,
    MAX(CASE WHEN effect = 'allow' THEN 1 ELSE 0 END) AS has_allow,
    MAX(CASE WHEN effect = 'deny' THEN 1 ELSE 0 END) AS has_deny
  FROM public.auth_user_permission_overrides
  GROUP BY user_id, permission_id
), all_candidates AS (
  SELECT user_id, permission_id FROM role_grants
  UNION
  SELECT user_id, permission_id FROM user_overrides
)
SELECT
  c.user_id,
  pk.key AS permission_key,
  pk.label AS permission_label,
  pk.module,
  pk.scope,
  CASE
    WHEN COALESCE(uo.has_deny, 0) = 1 THEN FALSE
    WHEN COALESCE(uo.has_allow, 0) = 1 THEN TRUE
    WHEN rg.granted_by_role IS TRUE THEN TRUE
    ELSE FALSE
  END AS is_allowed,
  CASE
    WHEN COALESCE(uo.has_deny, 0) = 1 THEN 'user-deny'
    WHEN COALESCE(uo.has_allow, 0) = 1 THEN 'user-allow'
    WHEN rg.granted_by_role IS TRUE THEN 'role'
    ELSE 'none'
  END AS source
FROM all_candidates c
JOIN public.auth_permission_keys pk ON pk.id = c.permission_id
LEFT JOIN role_grants rg ON rg.user_id = c.user_id AND rg.permission_id = c.permission_id
LEFT JOIN user_overrides uo ON uo.user_id = c.user_id AND uo.permission_id = c.permission_id;

COMMIT;

-- ============================================================
-- SCHEMA COMPLETE
-- ============================================================
-- Next step: Run seed_default_data.sql to insert default data.
-- ============================================================
