// Auto-generated by scripts/generate-env.mjs (dotenv + process.env) — do not edit.
// Regenerated when you run `npm start` or `npm run build`.

export const ENV = {
  NG_APP_API_BASE_URL: 'http://localhost:3000',
} as const;
